# -----------------------------
# VARIABLES
# -----------------------------

RESOURCE_GROUP="YourResourceGroup"
LOCATION="eastus2"

MIGRATION_SERVICE="YourMigrationService"

SUBSCRIPTION_ID="YourSubscription"

SOURCE_SERVER="YourSourceServer"
SOURCE_DB="YourSourceDB"
SOURCE_USER="YourSourceUser"
SOURCE_PASSWORD="YourSourcePassword"

TARGET_SERVER="YourTargetServer"
TARGET_DB="YourTargetDB"
TARGET_USER="YourTargetUser"
TARGET_PASSWORD="YourTargetPassword"

ACCESS_TOKEN=$(az account get-access-token \
    --resource https://database.windows.net \
    --query accessToken \
    --output tsv)