[linux_vm]
azure-vm-01 ansible_host=20.127.116.59

[linux_vm:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=/home/hardeymolhar/.ssh/dev/dev-key
ansible_connection=ssh

[windows]
win-dev-vm-1 ansible_host=20.127.99.40

[windows:vars]
ansible_user=azureuser
ansible_password=r3P1iKa5x_123
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore